### PR TITLE
SPRT-149: Fixing pagination issues

### PR DESCRIPTION
**Pull request by PabloBerrettoni**
Fixing some pagination problems suggested by @olea on this issue: https://github.com/PukaraES/Cicerone/issues/26
Now the page shows how many pages there are before any interaction with it.
It also goes back to one if we change the category or search another location.
And the mobile view that was previously broken was now fixed.

### CODE REVIEW

**Comment by olea** [comment]
It looks better but I think I've found some problem.

1. open the application
2. navigate with <- and ->, randomly if you wish
3. click on the number of the active page, if you are in the N page, clicking in the button «N»
4. application gets blank 8-|

Another one: if you change to another view (Monuments/Natual/Others) the page number showed in the new view it's the same number in the previous one, which is weird. Worst is at same time page numbering has been reset to 1. How to check:

1. choose a view and navigate to a selected page number N, remember the number and the elements listed
2. go to another view and navigate to the precise same number
3. change to the first view and check application lists the same contents of page N but pagination says 1.

**Comment by PabloBerrettoni** [comment]
@olea @olea The errors mentioned above are fixed by the last commit

**Comment by njrzr** [comment]
@PabloBerrettoni I checked the changes and looks good, but, you tried to update the pagination?, because in cases where the results are 9 or less, shows one button, but when I searched for other places, like Sevilla, the buttons doesn't update and show one and updates when next is selected, and well it feels odd when this happens, see it an try to fix it.

**Comment by olea** [comment]
As far i can check seems https://github.com/PukaraES/Cicerone/issues/26 is fixed.

**Pull request merged**
