### PR TITLE
SPRT-148 Change size to images

### PR DESCRIPTION
**Pull request by facuzero**
change sizes to make the image complete in the box

### CODE REVIEW

**Comment by njrzr** [comment]
@PabloBerrettoni @facuzero I checked the change in the wikilocal site, and the main image isn't centered and the blurred one is streched try that the blur one cover the element.

**Comment by facuzero** [comment]
@njrzr i think i fixed

**Comment by olea** [comment]
Checking this example: https://wikilocal.pukara.es/places/Q9088891/place-details : 
* image not horizontally centered;
* image height is smaller than the full space availiable;
* I think is wrong to fill aaaall wide space as a rectangle, aesthetically is better to just create an square (square size equal to image height), center the image horizontally and blur filling the square unused space.

**Review by njrzr — APPROVED** [review]

**Comment by njrzr** [comment]
@facuzero it's all good, I made some minor changes to what you did, I will approve the PR

**Pull request merged**
