### PR TITLE
WIK-16: Continuos Deployment

### PR DESCRIPTION
**Pull request by PabloBerrettoni**
Whenever a push is made into the Main branch it is automatically deployed in the production enviroment.

### CODE REVIEW

**Review by eddymdz — COMMENTED** [review]
@PabloBerrettoni I don't understand your changes, you need to you need to consider that we still need a development environment. I mean, with your changes from my point of view breaks the development environment. (c.c. @njrzr)

**Comment by PabloBerrettoni** [comment]
> @PabloBerrettoni I don't understand your changes, you need to you need to consider that we still need a development environment. I mean, with your changes from my point of view breaks the development environment. (c.c. @njrzr)

@eddymdz If you look at the CI file there you can see that whenever a PR is made the changes from that PR will be deployed in the development branch. This CD file will deploy those changes only when something is pushed into the branch.

**Comment by njrzr** [comment]
@eddymdz what @PabloBerrettoni did is that the files are uploading to cicerone.guide site, and these are only pushed when a PR is accepted, not created like the other action that pushes to wikilocal.pukara.es (that is supposed to be the dev site for cicerone). If I understand right, are you asking for a development domain under cicerone.guide, like dev.cicerone.guide?

**Comment by eddymdz** [comment]
@njrzr @PabloBerrettoni is not relevant the domain for development purposes. We need the current app working on cicerone.guide without broke the development flow.

**Review by eddymdz — APPROVED** [review]
Good for me

**Comment by eddymdz** [comment]
@njrzr after your approval, please merge these changes

**Review by njrzr — APPROVED** [review]

**Pull request merged**
