### PR TITLE
SPRT-127: Implement a docker environment

### PR DESCRIPTION
**Pull request by gnaomi0**
@eddymdz I added a docker-compose.yml because we using a public image. Also, the application only works for me when I declare the host. Let me know if we need some changes in this.

### CODE REVIEW

**Comment by njrzr** [comment]
@eddymdz do you need help? I can check this, tell me what I have to see, and review what @gnaomi0 did.

**Review by eddymdz — COMMENTED** [review]
@gnaomi0 your changes doesn't work for me, so please take in mind:

- Use the LTS Docker image for Node (don't use latest tag)
- Provide a Dockerfile or use a image not both

**Comment by MatiasMinchaca** [comment]
@gnaomi0  before creating the direct image of node en el service what I would do is create a Dockerfile with the configurations that the container need

- I leave you this reference to create the dockerfile:
    [https://dev.to/vishwasnarayan5/](https://dev.to/vishwasnarayan5/docker-for-the-frontend-and-backend-development-just-for-local-testing-not-for-the-deployment-1470)

### Remember  
  In the docker-compose.yml
  - you need to specify to build:
     - the context that is the root folder in ' context: '
     - and where is the Dockerfile located in ' dockerfile: '
  - put the project name specifying the latest version in ' image: '
  - enter the command to run the project in ' command: ' (I recommend having a different docker-compose both for development and production)

**Review by eddymdz — APPROVED** [review]
@gnaomi0 @MatiasMinchaca very good

**Pull request merged**
